repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-toml
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: fix-encoding-pragma
    -   id: detect-private-key
    -   id: check-added-large-files
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: ["-c", "python/pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]
